### ISSUE TITLE
Recommended way to set default user?

### ISSUE THREAD

**Issue by jonpugh** [geerlingguy/ansible-role-drupal-console#10]
I am adding this role to get Drupal Console into Devshop...

This means I'd like to run things as the `aegir` user, so I'm forking this playbook to add that, maybe as a variable?

I figured I'd run it by you to see what you think the best way to go about this is:

here's what I'm thinking...

```
- name: Run Drupal Console init.
  shell: >
    php {{ drupal_console_path }} init
    creates={{ drupal_console_config }}
  become: yes
  become_user: "{{ drupal_console_user }}"
```

Thoughts?

**Comment by geerlingguy** [comment]
@jonpugh - Is the `aegir` user the user that Ansible is logged in as? If so, maybe it could be a `become: no` instead, and that way the task would just run as that user.

Otherwise, yes, you'd need to use `become` (which uses sudo) to switch to that user.
